services:
  tests:
    build: .
    image: nimword
    volumes:
      - .:/usr/src/app
    command: nimble test

  docs:
    build: .
    image: nimword
    volumes:
      - .:/usr/src/app
    command: nimble apis
