name: Run Tests

on:
  push:
    branches:
      - devel
      - main
  pull_request:
    branches:
      - devel
      - main

jobs:
  Tests:
    strategy:
      matrix:
        nimversion: 
          - binary:2.0.0
          - binary:1.6.10
        os:
          - ubuntu-latest
          #- windows-latest
          #- macOS-latest
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    
    name: Nim ${{ matrix.nimversion }} - ${{ matrix.os }}


    steps:
      - uses: actions/checkout@v1
      - uses: iffy/install-nim@v4
        with:
          version: ${{ matrix.nimversion }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Test
        run: |
          /bin/bash
          apt-get update && apt-get install -y openssl libsodium-dev xz-utils
          apt-get install -y argon2
          nimble install -y
          nimble test
          
  Docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docs
        run: docker-compose run docs

